### ISSUE TITLE
Problems with data set up

### ISSUE THREAD

**Issue by LaiaWilson** [tudelft3d/City4CFD#13]
Hi! 
I have to work with city4CFD for my graduation project. I have basic experience with programing or these type of softwares, so I have been struggling in getting everything I need to prepare the CFD data, and I've been stuck on the same issue for days. 

This is the error I got after I input: ~/City4CFD/build/city4cfd /home/wilai/config_bpg.json --output_dir /home/wilai/results

![image](https://github.com/tudelft3d/3dfier/assets/97634257/fb0689c2-c2c5-4cde-b711-60b8fec896c9)

This is the file config_bpg.json I got: 
{
  "timeStep": 0.01,
  "simulationDuration": 10,
  "convergenceCriteria": 0.000001,
  "point_of_interest": [
      85376,
      446125
  ],
  "influence_region": 0,
  "domain_bnd": "Rectangle",
  "dimensions": {
      "length": 10,
      "width": 50,
      "height": 30
  },
  "top_height": 100,
  "geometryFile": "/home/wilai/COW/COW.stl",
  "meshSize": 0.1,
  "meshRefinementLevels": 2,
  "fluidDensity": 1000,
  "fluidViscosity": 0.001,
  "inletVelocity": 1,
  "outletPressure": 0,
  "wallFriction": 0.005,
  "numericalMethod": "FiniteVolume",
  "turbulenceModel": "k-epsilon",
  "solverIterations": 1000,
  "output_format": "stl",
  "output_file_name": "COW.stl",
  "output_separately": false,
  "outputFrequency": 100,
  "bnd_type_bpg": "Rectangle",
  "flow_direction": [
      1,
      1
  ],
  "building_percentile": 0.000001,
  "edge_max_len": 0.000001
}

**Comment by ipadjen** [comment]
Hello,

Check the ways to setup the influence region here:
https://github.com/tudelft3d/City4CFD/wiki/Configuration-File#domain-dimensions

It seems you were aiming for something similar to:
``"influence_region": [[88200, 123400], [88300, 123400], [88300, 123500] [88200, 123500]]``.

If you want to manually define a rectangle (or any other polygon for that matter), you would have to type the coordinates of points in your local coordinate system.

**Comment by LaiaWilson** [comment]
Thank you for the response. I have not been able to solve it by using this, I get a different type of error. Right now this is what I am getting. 
![image](https://github.com/tudelft3d/City4CFD/assets/97634257/ff09803b-b65c-44d7-9269-aad9c8114f50)

This is my code:
{
  "point_clouds" :
  {
    "ground": "/home/wilai/files_city4CFD/real_case_floor.ply",
    "buildings" : "/home/wilai/files_city4CFD/real_case_building.ply"
  },
  "polygons" : [
    {
      "type": "Building",
      "path": "/home/wilai/files_city4CFD/real_buildings.geojson",
      "unique_id": "gid"
    },
    {
      "type":       "SurfaceLayer",
      "path":       "/home/wilai/files_city4CFD/real_water.geojson",
      "layer_name": "Water"
    }
  ],

  "point_of_interest": [85376, 446125],
  "influence_region": 800,
  "domain_bnd":         null,
  "top_height":         300,

  "bnd_type_bpg":      "Rectangle",
  "bpg_blockage_ratio": false,        
  "flow_direction":     [1, 1],
  "buffer_region":      20,
  "reconstruct_boundaries": true,

  "terrain_thinning": 10,
  "smooth_terrain":   {
    "iterations": 1,
    "max_pts": 100000
  },

  "lod": "1.2",
  "building_percentile": 90,

  "edge_max_len": 5,

  "output_file_name":  "Mesh",
  "output_format":     "obj",
  "output_separately":  true,

  "output_log": true,
  "log_file": "logFile.log"
}

**Comment by ipadjen** [comment]
So the newest message indicates misalignment between influence region coordinates and your actual buildings. I can see right off the bat that your `point of interest` is exactly the same as in the TUD campus example, whereas you probably used different case.

Also, the loaded buildings and water polygons are in coordinate system EPSG:3857 which is not really a local coordinate system. I would presume your buildings points are in some local coordinate system whose origin is relatively close to your actual case, such as EPSG:28992 in case of the Netherlands .

My suggestion is to read the wiki section on coordinate alignment (https://github.com/tudelft3d/City4CFD/wiki/Aligning-polygons-and-point-clouds) and the tutorial where some of this alignment is explained (https://github.com/tudelft3d/City4CFD/wiki/Delfhsaven,-Rotterdam,-The-Netherlands)
