### ISSUE TITLE
Any public dataset

### ISSUE THREAD

**Issue by dyu62** [tudelft3d/City4CFD#17]
Amazing work! Is there any already generated public dataset for tasks like building classification?

**Comment by dyu62** [comment]
> Hello, thank you!
> 
> Can you please elaborate a bit more? Do you mean a repo that contains a code that can classify buildings for you?

We are developing a model that simultaneously considers both terrain and building shapes, and we need a publicly available dataset to validate the model. If I understand correctly, this algorithm can generate real-world buildings along with surrounding terrain as polygon meshes. If we have labels for building types (possibly house, school, church, etc.), we could potentially construct a benchmark dataset for model testing. I've noticed that your team has published the 3DBAG dataset, which closely aligns with our requirements but without terrain and building labels. Have you already constructed or do you plan to publish a new dataset that includes terrain along with building labels?

**Comment by ipadjen** [comment]
We currently have no plans on publishing datasets (other than some examples) with City4CFD as it is specific to urban flow simulations.

However, you can ask the same question to the 3DBAG team https://docs.3dbag.nl/en/contact/.

Hope that helps.
