### ISSUE TITLE
Water is terrain layer in output

### ISSUE THREAD

**Issue by ewesterling** [tudelft3d/City4CFD#19]
Hey,

I used city4cfd to create the geometry over a rowing course (bosbaan, amstelveen). It worked very good, until I wanted to make my domain boundaries smaller, now the water is not created anymore in the output file. First, my domain boundaries were around 300m around the water, and I decreased it to approximately 200m. Is there a way that I can make my domain boundaries smaller and still get a water layer in the output?

Thank you in advance,
Emilie

**Comment by ipadjen** [comment]
Hi Emilie!

You can get around that by clipping/splitting your water polygon. City4CFD skips surface layers that reach outside the domain extent. So you could, for example, use the 'Split Features' function in QGIS to split your water polygons close to domain boundaries.

You can also check https://github.com/tudelft3d/City4CFD/issues/4 as a similar issue, maybe helps.

**Comment by ewesterling** [comment]
Yes it worked, thank you very much!
