### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by jflsousa** [tudelft3d/City4CFD#2]
OS: Ubuntu 22.04.2 LTS

[ 63%] Building CXX object CMakeFiles/city4cfd.dir/src/Building.cpp.o
[ 64%] Building CXX object CMakeFiles/city4cfd.dir/src/Config.cpp.o
[ 65%] Building CXX object CMakeFiles/city4cfd.dir/src/ImportedBuilding.cpp.o
[ 67%] Building CXX object CMakeFiles/city4cfd.dir/src/LoD12.cpp.o
[ 68%] Building CXX object CMakeFiles/city4cfd.dir/src/Map3d.cpp.o
[ 69%] Building CXX object CMakeFiles/city4cfd.dir/src/PointCloud.cpp.o
[ 70%] Building CXX object CMakeFiles/city4cfd.dir/src/PolyFeature.cpp.o
/home/fernandj/tools/City4CFD/src/PolyFeature.cpp:36:10: fatal error: CGAL/Barycentric_coordinates_2/Triangle_coordinates_2.h: No such file or directory
   36 | #include <CGAL/Barycentric_coordinates_2/Triangle_coordinates_2.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/city4cfd.dir/build.make:188: CMakeFiles/city4cfd.dir/src/PolyFeature.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: CMakeFiles/city4cfd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by ipadjen** [comment]
Hello! Triangle_coordinates_2.h was deprecated and ultimately removed from CGAL. It looks to me as a City4CFD/CGAL version mismatch. I just tried compiling City4CFD on a fresh Ubuntu 22.04 docker image and it works.

Are you using the newest version of City4CFD?

**Comment by ipadjen** [comment]
Ah okay, found it. It happens when compiling in the debug mode.

**Comment by ipadjen** [comment]
Fixed in 75bf733.

**Comment by jflsousa** [comment]
Thanks! It work fine now :)
