### ISSUE TITLE
Regarding the severe deformation of the generated model.

### ISSUE THREAD

**Issue by Xtian-hub** [tudelft3d/City4CFD#23]
![3acd8355bcbb0586e89be8b341588e7](https://github.com/user-attachments/assets/4efc0f04-36c4-49bd-8c7b-bebb2a77dbbe)
![4ac84ad0f8959d12e25a6e72b52e209](https://github.com/user-attachments/assets/f960d871-ebec-4799-b44f-4410f9e82afc)
The image I provided is of the model I generated, and I don't quite understand why my model is so severely incomplete. Additionally, no matter how I modify the config file, the generated results do not change, except for adjustments in lod from 2.2 to 1.2. Here is the configuration file I set up; it may have some unusual settings, but the generated results remain unchanged.
{
  "point_clouds" :
  {
    "ground": "point_cloud/merged_ground_pcl.las",
    "buildings" : "point_cloud/merged_building_pcl.las"
  },
  "polygons" : [
    {
      "type": "Building",
      "path": "polygons/bf_utm_28355_test.geojson",
      "unique_id": "gid"
    },
    {
      "type": "SurfaceLayer",
      "path": "polygons/glands_28355.geojson",
       "layer_name" : "Vegetation"
    },
    {
      "type":       "SurfaceLayer",
      "path":       "polygons/water_28355.geojson",
      "layer_name": "Water"
    }
  ],
  "reconstruction_regions": [
    // {
    //   "influence_region":  30,
    //   "lod": "1.2"
    // },
    {
      "influence_region":  "polygons/building_zone_28355.geojson",
      "lod": "2.2"
    }
  ],

  "point_of_interest": [150 , -600],
  "domain_bnd":        "polygons/15hmax_zone_28355.geojson",
  "top_height":        50,
  "flow_direction":    [1, 1],
  "buffer_region":     10,
  "reconstruct_boundaries": true,

  "terrain_thinning": 10,
  "smooth_terrain":   {
    "iterations": 100,
    "max_pts": 10000
  },

  "building_percentile": 1,

  "edge_max_len": 15,

  "output_file_name":  "Mesh3",
  "output_format":     "obj",
  "output_separately": true,

  "output_log": true,
  "log_file": "logFile.log"
}

**Comment by ipadjen** [comment]
Hello,

Can you please provide the minimum example (point cloud, polygons) for that building?

**Comment by Xtian-hub** [comment]
Hello, 
I seem to have found the cause of the issue. I resolved it by splitting the building footprints into non-overlapping small patches. Thank you for your response.
