### ISSUE TITLE
Problem reconstructing water surface

### ISSUE THREAD

**Issue by jflsousa** [tudelft3d/City4CFD#4]
city4CFD is only creating terrain.obj and buildings.obj and nothing for the water. Here is the config file:
I have tried:
1) The point cloud for the terrain to include the water (height=0)  
2) The point cloud not including the removing the water points.
With the same result
  
     {
      "point_clouds" :
      {
        "ground": "terrain_clean.xyz"
        //"ground": "water.xyz"
      },
  
      "polygons" : [
          {
          "type": "Building",
          "path": "bld_test.geojson",
          "unique_id": "Name",
          "height_attribute": "height",
          "height_attribute_advantage": true
          },
          {
          "type":       "SurfaceLayer",
          "path":       "waterRegion.geojson",
          "layer_name": "Water"
          }
      
      
      ],
  
    
      "point_of_interest": [0, 0],
      "influence_region":  "influenceRegion.geojson",
      "domain_bnd":        "domain.geojson",
      "top_height":        150,
      "flow_direction":    [1, 1],
      "buffer_region":     40,
      "reconstruct_boundaries": false,
    
      "terrain_thinning": 10,
      "smooth_terrain":   {
        "iterations": 1,
        "max_pts": 100000
      },
    
    
      "lod": "1.2",
      "building_percentile": 90,
    
      "edge_max_len": 2,
    
      "output_file_name":  "Mesh",
      "output_format":     "obj",
      "output_separately": true,
    
      "output_log": true,
      "log_file": "logFile.log"
    }
  

Point cloud data for the terrain:
![image](https://github.com/tudelft3d/City4CFD/assets/42591462/268c2d70-187a-4dce-bc37-c04d20577a11)

polygon for the water:
![image](https://github.com/tudelft3d/City4CFD/assets/42591462/f372024a-f327-400a-b95b-ee4b3f5c3de3)

**Comment by ipadjen** [comment]
Seems that your water surfaces consist of few large polygons? The code will not imprint polygons that have vertices outside the domain extent. Have you maybe tried making your domain extent bigger?

If you clipped your water polygons with the domain boundary polygon, try clipping it a bit more around the edges.

**Comment by jflsousa** [comment]
Hi Ivan,
That worked! 
Thanks for the help!

**Comment by ipadjen** [comment]
Great!
