### ISSUE TITLE
not all water surfaces are flattened

### ISSUE THREAD

**Issue by frank984321587** [tudelft3d/City4CFD#7]
I used a water layer for the imprinting, with the setting to flatten the surface.
But it seems that some water surfaces are flat, but some are not. image below uses calc to show the Z-coor on the water layer.
![water](https://github.com/tudelft3d/City4CFD/assets/145677128/cc0f58d8-d775-4662-a0b8-62f52931e47b)

Any idea how to fix this?

{
  "point_clouds" :
  {
    "ground": "point_cloud/ground_in.ply"
  },
  "polygons" : [
    //{
    //  "type": "SurfaceLayer",
    //  "path": "polygons/Vegetation.geojson",
    //   "layer_name" : "Vegetation"
    //},
    {
      "type":       "SurfaceLayer",
      "path":       "polygons/water3.geojson",
      //"path":       "polygons/water2.dxf",
      "layer_name": "Water",
      "flatten_surface":         true,       // Optional - set all points of the surface layer to the same height
      "flatten_vertical_border": false,       // Optional - enforce vertical walls between terrain 
      "surface_percentile": 30               // Percentile of all points of the surface layer to set the height, required if flatten_surface is true
    }
  ],
  "import_geometries": {
    "path": "import_buildings/buildings.ply",
    "advantage": true,
    "true_height": true,
    "lod": "1.3"
  },

  "point_of_interest": [0, 0], //[96250, 436900],
  "influence_region":  500,
  "domain_bnd":        null,
  "bnd_type_bpg":    "Round",     // Round, Rectangle, Oval. Matters only if using BPG
  "top_height":        150,
  "flow_direction":    [1, 0],
  "buffer_region":     0,
  "reconstruct_boundaries": false,

  "terrain_thinning": 50,
  "smooth_terrain":   {
    "iterations": 3,
    "max_pts": 1000000
  },
  "flat_terrain":     false,          // Optional - make terrain flat

  "lod": "1.2",
  "building_percentile": 90,

  "edge_max_len": 5,

  "output_file_name":  "Mesh",
  "output_format":     "stl",
  "output_separately": true,

  "output_log": true,
  "log_file": "logFile.log"
}

**Comment by ipadjen** [comment]
Does this happen only when there is a building adjacent to the water polygon? The code at the moment skips flattening polygons adjacent to buildings as it might interfere with the building reconstruction.

I might be able to come up with a smarter solution in this specific case.

**Comment by frank984321587** [comment]
It looks like that yes. The 2 surfaces that failed flattening are touching a building.
Perhaps set this check behind a toggle, so be able to force a flatten?
And a mention in the log would be nice.

**Comment by ipadjen** [comment]
Hello, I made a pull request in https://github.com/tudelft3d/City4CFD/pull/10 that aims to solve this issue. Are you maybe able to test it out on different datasets other than the TUD example and let me know if it performs well?
https://github.com/tudelft3d/City4CFD/tree/improve/poly-flattening is the branch to pull and compile.

**Comment by frank984321587** [comment]
Hi Ivan,

I got the time to take it for another spin, and now it seems to work good (all colored water surfaces are at the same height):
***@***.***

The dataset and settings I used are in this zip folder:
[?zip icon] https://corporateroot-my.sharepoint.com/:u:/g/personal/frank_van_gool_rhdhv_com/EWdHwroi0rFNp7L8i7pWEsMBLfKmRJlubSrCrlMItn7hsQ?e=UCR9eq

Thanks for fixing, and hope that my input helps.

Met vriendelijke groeten,
Frank

ir. Frank van Gool
Numerical Simulation Expert | Advanced Technology & Research Group<https://www.royalhaskoningdhv.com/en-gb/services/a-z-services/advanced-technology-and-research/7286> | Industry & Buildings
T +31 88 34 83 199 | E ***@***.******@***.***> | W www.royalhaskoningdhv.com<http://www.royalhaskoningdhv.com/>

**Comment by ipadjen** [comment]
Thanks for checking!

**Comment by ipadjen** [comment]
Fix merged into develop.
