### ISSUE TITLE
Problem compiling on OpenSUSE Leap 15.3

### ISSUE THREAD

**Issue by BW-Sampath** [tudelft3d/City4CFD#9]
I cannot compile the software on OpenSUSE Leap 15.3. CMake works fine without any errors, but the compilation fails. I tried compiling with 10 cores, FYI. I'm attaching both logs of CMake and make. 
[log.make.txt](https://github.com/tudelft3d/City4CFD/files/12880680/log.make.txt)
[log.cmake.txt](https://github.com/tudelft3d/City4CFD/files/12880681/log.cmake.txt)

The errors seem to originate due to the lines 
https://github.com/tudelft3d/City4CFD/blob/99ace1360d26c0caf3a4aed1224734b18b75d4e1/src/Map3d.cpp#L337
https://github.com/tudelft3d/City4CFD/blob/99ace1360d26c0caf3a4aed1224734b18b75d4e1/src/PointCloud.cpp#L245

Replacing the two lines with 
```
#pragma omp parallel
```
seems to give a successful compilation, but running the TUDcampus example case throws a segmentation fault error. Any help would be appreciated

**Comment by ipadjen** [comment]
Hi there. Thanks for including the logs.

It seems that the GCC compiler version 7 doesn't like the way things are handled with OpenMP. Using GCC 9 (should be available through package managers in Leap 15.3) would work. I will mention that in the requirements.

**Comment by BW-Sampath** [comment]
Hi. Thanks for the quick response. Installing GCC 9 seems to have solved this compiling issue. Now I can run the example case without any problems

**Comment by ipadjen** [comment]
Great! Closing this then.
